<a href="https://colab.research.google.com/github/gokulnath2005offcial-eng/DSA-Corporate-Training-and-Interviews-based-question---17-30-june-2026-/blob/main/AIML_CT_03_07_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day : 1 Introuduction to aiml & its Rodemap

Day : 2 Foundation of python for Data science

Day : 3 Numpy fundementals

In [ ]:
# valid Variable

name = "Gokul"
age = 20
student_name = "Rahul"
_marks = 95
salary2026 = 50000
PI = 3.14

print(name)
print(age)
print(student_name)
print(_marks)
print(salary2026)
print(PI)

Gokul
20
Rahul
95
50000
3.14


In [ ]:
#invalid veriables

2name = "Gokul"        # Starts with a number
student-name = "Rahul" # Hyphen (-) is not allowed
my name = "John"       # Space is not allowed
class = "Python"       # 'class' is a Python keyword
for = 10               # 'for' is a Python keyword
@name = "Sam"          # Special characters are not allowed

SyntaxError: invalid decimal literal (3124884502.py, line 1)

Foundation of python for Data science :

List

Float

Decimal

In [ ]:
from decimal import Decimal

# Integer
age = 20

# Float
height = 5.8

# Decimal
price = Decimal("99.99")

print("Age:", age)
print("Height:", height)
print("Price:", price)

Age: 20
Height: 5.8
Price: 99.99


String data type :

In [ ]:
first_name = "Gokul"
last_name = "Nath"

full_name = first_name + " " + last_name

print(full_name)
print(len(full_name))
print(full_name.upper())
print(full_name.lower())

Gokul Nath
10
GOKUL NATH
gokul nath


String malupulation :

In [ ]:
# Sequential Data Types in Python

# String
name = "Python Programming"
print("String:")
print(name)
print("First Character:", name[0])
print("Length:", len(name))
print()

# List
numbers = [10, 20, 30, 40]
print("List:")
print(numbers)
numbers.append(50)
print("After Append:", numbers)
print("Second Element:", numbers[1])
print()

# Tuple
marks = (85, 90, 95, 100)
print("Tuple:")
print(marks)
print("Third Element:", marks[2])
print()

# Range
print("Range:")
for i in range(1, 6):
    print(i, end=" ")
print("\n")

# elements using index
print("Indexing Examples:")
print("String Index 2:", name[2])
print("List Index 3:", numbers[3])
print("Tuple Index 1:", marks[1])

# Checking data types
print("\nData Types:")
print(type(name))
print(type(numbers))
print(type(marks))
print(type(range(1, 6)))

String:
Python Programming
First Character: P
Length: 18

List:
[10, 20, 30, 40]
After Append: [10, 20, 30, 40, 50]
Second Element: 20

Tuple:
(85, 90, 95, 100)
Third Element: 95

Range:
1 2 3 4 5 

Indexing Examples:
String Index 2: t
List Index 3: 40
Tuple Index 1: 90

Data Types:
<class 'str'>
<class 'list'>
<class 'tuple'>
<class 'range'>


In [ ]:
# Float Example

price = 99.99
height = 5.8
temperature = 36.5

print("Price:", price)
print("Height:", height)
print("Temperature:", temperature)

print(type(price))
print(type(height))
print(type(temperature))

Price: 99.99
Height: 5.8
Temperature: 36.5
<class 'float'>
<class 'float'>
<class 'float'>


In [ ]:
# Integer Example

age = 20
marks = 95
salary = 50000

print("Age:", age)
print("Marks:", marks)
print("Salary:", salary)

print(type(age))
print(type(marks))
print(type(salary))

Age: 20
Marks: 95
Salary: 50000
<class 'int'>
<class 'int'>
<class 'int'>


In [ ]:
# Boolean

is_student = True
is_employee = False

print("Is Student:", is_student)
print("Is Employee:", is_employee)

print(type(is_student))
print(type(is_employee))

Is Student: True
Is Employee: False
<class 'bool'>
<class 'bool'>


In [ ]:
# Complex Data Type in Python

# Creating Complex Numbers
num1 = 3 + 4j
num2 = 5 + 2j

# Display Complex Numbers
print("Complex Number 1:", num1)
print("Complex Number 2:", num2)

# Check Data Type
print("Data Type of num1:", type(num1))
print("Data Type of num2:", type(num2))

# Arithmetic Operations
print("\nArithmetic Operations")
print("Addition:", num1 + num2)
print("Subtraction:", num1 - num2)
print("Multiplication:", num1 * num2)
print("Division:", num1 / num2)

# Real and Imaginary Parts
print("\nReal and Imaginary Parts")
print("Real Part of num1:", num1.real)
print("Imaginary Part of num1:", num1.imag)

# Creating Complex Number using complex() Function
num3 = complex(10, 20)

print("\nComplex Number using complex() Function:", num3)
print("Real Part:", num3.real)
print("Imaginary Part:", num3.imag)

# Comparison
print("\nComparison")
print("num1 == num2:", num1 == num2)
print("num1 != num2:", num1 != num2)

Complex Number 1: (3+4j)
Complex Number 2: (5+2j)
Data Type of num1: <class 'complex'>
Data Type of num2: <class 'complex'>

Arithmetic Operations
Addition: (8+6j)
Subtraction: (-2+2j)
Multiplication: (7+26j)
Division: (0.793103448275862+0.48275862068965514j)

Real and Imaginary Parts
Real Part of num1: 3.0
Imaginary Part of num1: 4.0

Complex Number using complex() Function: (10+20j)
Real Part: 10.0
Imaginary Part: 20.0

Comparison
num1 == num2: False
num1 != num2: True


DATA TYPE :

In [ ]:
# Integer (int)
age = 20

# Float (float)
height = 5.8

# String (str)
name = "Gokul"

# Boolean (bool)
is_student = True

# Complex (complex)
number = 2 + 3j

print(age)
print(height)
print(name)
print(is_student)
print(number)

print(type(age))
print(type(height))
print(type(name))
print(type(is_student))
print(type(number))

20
5.8
Gokul
True
(2+3j)
<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'complex'>


Python List Methods:

In [ ]:
# Creating a list
fruits = ["Apple", "Banana", "Cherry"]

print("Original List:", fruits)

# append()
fruits.append("Mango")
print("append():", fruits)

# extend()
fruits.extend(["Orange", "Grapes"])
print("extend():", fruits)

# insert()
fruits.insert(1, "Pineapple")
print("insert():", fruits)

# remove()
fruits.remove("Banana")
print("remove():", fruits)

# pop()
item = fruits.pop()
print("pop():", item)
print(fruits)

# index()
print("index of Apple:", fruits.index("Apple"))

# count()
numbers = [10, 20, 10, 30, 10]
print("count of 10:", numbers.count(10))

# sort()
numbers.sort()
print("sort():", numbers)

# reverse()
numbers.reverse()
print("reverse():", numbers)

# copy()
new_numbers = numbers.copy()
print("copy():", new_numbers)

# clear()
new_numbers.clear()
print("clear():", new_numbers)

Original List: ['Apple', 'Banana', 'Cherry']
append(): ['Apple', 'Banana', 'Cherry', 'Mango']
extend(): ['Apple', 'Banana', 'Cherry', 'Mango', 'Orange', 'Grapes']
insert(): ['Apple', 'Pineapple', 'Banana', 'Cherry', 'Mango', 'Orange', 'Grapes']
remove(): ['Apple', 'Pineapple', 'Cherry', 'Mango', 'Orange', 'Grapes']
pop(): Grapes
['Apple', 'Pineapple', 'Cherry', 'Mango', 'Orange']
index of Apple: 0
count of 10: 3
sort(): [10, 10, 10, 20, 30]
reverse(): [30, 20, 10, 10, 10]
copy(): [30, 20, 10, 10, 10]
clear(): []


Tuples Methods:

In [ ]:
# Creating a Tuple
fruits = ("Apple", "Banana", "Cherry", "Mango", "Orange")

print("Original Tuple:", fruits)

# Accessing Elements
print("\nFirst Element:", fruits[0])
print("Last Element:", fruits[-1])

# Slicing
print("\nFirst 3 Elements:", fruits[:3])
print("Last 2 Elements:", fruits[-2:])

# Length of Tuple
print("\nLength:", len(fruits))

# Membership Operators
print("\nIs Apple present?", "Apple" in fruits)
print("Is Grapes present?", "Grapes" in fruits)

# Concatenation
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)
result = tuple1 + tuple2
print("\nConcatenation:", result)

# Repetition
repeat = tuple1 * 2
print("Repetition:", repeat)

# count() Method
numbers = (10, 20, 30, 10, 40, 10)
print("\nCount of 10:", numbers.count(10))

# index() Method
print("Index of 30:", numbers.index(30))

# Built-in Functions
print("\nMaximum:", max(numbers))
print("Minimum:", min(numbers))
print("Sum:", sum(numbers))

# Sorted Function
print("Sorted:", sorted(numbers))

# Iterating Through Tuple
print("\nElements in Tuple:")
for item in fruits:
    print(item)

# Nested Tuple
student = ("Gokul", 20, ("Python", "SQL", "AI"))
print("\nNested Tuple:", student)
print("Course 1:", student[2][0])
print("Course 2:", student[2][1])

# Packing
packed = 100, 200, 300
print("\nPacked Tuple:", packed)

# Unpacking
a, b, c = packed
print("Unpacked Values:", a, b, c)

print("\nProgram Completed Successfully!")

Original Tuple: ('Apple', 'Banana', 'Cherry', 'Mango', 'Orange')

First Element: Apple
Last Element: Orange

First 3 Elements: ('Apple', 'Banana', 'Cherry')
Last 2 Elements: ('Mango', 'Orange')

Length: 5

Is Apple present? True
Is Grapes present? False

Concatenation: (1, 2, 3, 4, 5, 6)
Repetition: (1, 2, 3, 1, 2, 3)

Count of 10: 3
Index of 30: 2

Maximum: 40
Minimum: 10
Sum: 120
Sorted: [10, 10, 10, 20, 30, 40]

Elements in Tuple:
Apple
Banana
Cherry
Mango
Orange

Nested Tuple: ('Gokul', 20, ('Python', 'SQL', 'AI'))
Course 1: Python
Course 2: SQL

Packed Tuple: (100, 200, 300)
Unpacked Values: 100 200 300

Program Completed Successfully!


Dictionary Methods:

In [ ]:
# Creating a Dictionary
student = {
    "Name": "Gokul",
    "Age": 20,
    "Course": "Python",
    "Marks": 95
}

print("Original Dictionary:")
print(student)

# Accessing Values
print("\nName:", student["Name"])
print("Course:", student.get("Course"))

# keys()
print("\nKeys:")
print(student.keys())

# values()
print("\nValues:")
print(student.values())

# items()
print("\nItems:")
print(student.items())

# update()
student.update({"Age": 21, "City": "Chennai"})
print("\nAfter update():")
print(student)

# setdefault()
student.setdefault("College", "ABC College")
print("\nAfter setdefault():")
print(student)

# pop()
student.pop("Marks")
print("\nAfter pop('Marks'):")
print(student)

# popitem()
student.popitem()
print("\nAfter popitem():")
print(student)

# copy()
new_student = student.copy()
print("\nCopied Dictionary:")
print(new_student)

# Length
print("\nLength:", len(student))

# Membership
print("\nIs 'Name' present?", "Name" in student)

# Looping
print("\nDictionary Elements:")
for key, value in student.items():
    print(key, ":", value)

# clear()
student.clear()
print("\nAfter clear():")
print(student)

Original Dictionary:
{'Name': 'Gokul', 'Age': 20, 'Course': 'Python', 'Marks': 95}

Name: Gokul
Course: Python

Keys:
dict_keys(['Name', 'Age', 'Course', 'Marks'])

Values:
dict_values(['Gokul', 20, 'Python', 95])

Items:
dict_items([('Name', 'Gokul'), ('Age', 20), ('Course', 'Python'), ('Marks', 95)])

After update():
{'Name': 'Gokul', 'Age': 21, 'Course': 'Python', 'Marks': 95, 'City': 'Chennai'}

After setdefault():
{'Name': 'Gokul', 'Age': 21, 'Course': 'Python', 'Marks': 95, 'City': 'Chennai', 'College': 'ABC College'}

After pop('Marks'):
{'Name': 'Gokul', 'Age': 21, 'Course': 'Python', 'City': 'Chennai', 'College': 'ABC College'}

After popitem():
{'Name': 'Gokul', 'Age': 21, 'Course': 'Python', 'City': 'Chennai'}

Copied Dictionary:
{'Name': 'Gokul', 'Age': 21, 'Course': 'Python', 'City': 'Chennai'}

Length: 4

Is 'Name' present? True

Dictionary Elements:
Name : Gokul
Age : 21
Course : Python
City : Chennai

After clear():
{}


DAY :2

In [ ]:
import numpy as np

# 1D Array
A1 = np.array([1, 2, 3, 4, 5])
print(A1)

# 2D Array
A2 = np.array([[1, 2, 3],
               [4, 5, 6]])
print(A2)

# 3D Array
A3 = np.array([[[1, 2, 3], [4, 5, 6]],
               [[7, 8, 9], [10, 11, 12]]])
print(A3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


ZERO ARRAY :

In [ ]:
import numpy as np

a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


2D ARRAY


In [ ]:
import numpy as np

a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Ones Array :

In [ ]:
import numpy as np

a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


2D Ones Array :

In [ ]:
import numpy as np

a = np.ones((2, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


Empty Array :

In [ ]:
import numpy as np

a = np.empty((2, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


Identity Matrix :

In [ ]:
import numpy as np

a = np.eye(4)
print(a)

In [ ]:
import numpy as np

a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Full Array :

In [ ]:
import numpy as np

a = np.full((3, 3), 7)
print(a)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


Range Array :

In [ ]:
import numpy as np

a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


Evenly Spaced Array :

In [ ]:
import numpy as np

a = np.linspace(1, 10, 5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


Random Array :

In [ ]:
import numpy as np

a = np.random.rand(3, 3)
print(a)

[[0.53977833 0.58364236 0.68450107]
 [0.11324403 0.56443627 0.94169205]
 [0.84973644 0.57562339 0.77954229]]


Random Integer Array :

In [ ]:
import numpy as np

a = np.random.randint(1, 50, (3, 4))
print(a)

[[22 18 31 48]
 [12 29  3  2]
 [11 46 48 19]]


Diagonal Array :

In [ ]:
import numpy as np

a = np.diag([5, 10, 15, 20])
print(a)

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]


OVERALL PROGRAM :

In [ ]:
import numpy as np

print("Zeros Array")
print(np.zeros((2,3)))

print("\nOnes Array")
print(np.ones((2,3)))

print("\nEmpty Array")
print(np.empty((2,3)))

print("\nIdentity Matrix")
print(np.eye(4))

print("\nFull Array")
print(np.full((3,3), 9))

print("\nRange Array")
print(np.arange(1,11))

print("\nLinspace Array")
print(np.linspace(0,100,11))

print("\nRandom Float Array")
print(np.random.rand(3,3))

print("\nRandom Integer Array")
print(np.random.randint(1,100,(3,3)))

print("\nDiagonal Matrix")
print(np.diag([2,4,6,8]))

Zeros Array
[[0. 0. 0.]
 [0. 0. 0.]]

Ones Array
[[1. 1. 1.]
 [1. 1. 1.]]

Empty Array
[[1. 1. 1.]
 [1. 1. 1.]]

Identity Matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Full Array
[[9 9 9]
 [9 9 9]
 [9 9 9]]

Range Array
[ 1  2  3  4  5  6  7  8  9 10]

Linspace Array
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]

Random Float Array
[[0.24176978 0.1627387  0.7037256 ]
 [0.16171714 0.30526208 0.43001736]
 [0.43436092 0.39238638 0.20325425]]

Random Integer Array
[[ 8 34 22]
 [ 1 41 78]
 [ 4 65 14]]

Diagonal Matrix
[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]


NumPy Array Arithmetic Operations (Using Two Arrays) :

In [ ]:
import numpy as np

# Create two arrays
A = np.array([10, 20, 30, 40, 50])
B = np.array([2, 4, 5, 8, 10])

# Addition
addition = A + B
print("Addition:")
print(addition)

# Subtraction
subtraction = A - B
print("\nSubtraction:")
print(subtraction)

# Multiplication
multiplication = A * B
print("\nMultiplication:")
print(multiplication)

# Division
division = A / B
print("\nDivision:")
print(division)

Addition:
[12 24 35 48 60]

Subtraction:
[ 8 16 25 32 40]

Multiplication:
[ 20  80 150 320 500]

Division:
[5. 5. 6. 5. 5.]


Using 2D Arrays :

In [ ]:
import numpy as np

# Create two 2D arrays
A = np.array([[10, 20],
              [30, 40]])

B = np.array([[2, 4],
              [5, 8]])

print("Array A:")
print(A)

print("\nArray B:")
print(B)

print("\nAddition:")
print(A + B)

print("\nSubtraction:")
print(A - B)

print("\nMultiplication:")
print(A * B)

print("\nDivision:")
print(A / B)

Array A:
[[10 20]
 [30 40]]

Array B:
[[2 4]
 [5 8]]

Addition:
[[12 24]
 [35 48]]

Subtraction:
[[ 8 16]
 [25 32]]

Multiplication:
[[ 20  80]
 [150 320]]

Division:
[[5. 5.]
 [6. 5.]]


Matrix Addition :

In [ ]:
import numpy as np

# Matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Matrix B
B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Matrix Addition
C = A + B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix Addition:")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Matrix Addition:
[[ 8 10 12]
 [14 16 18]]


Matrix Subtraction :

In [ ]:
import numpy as np

# Matrix A
A = np.array([[10, 20, 30],
              [40, 50, 60]])

# Matrix B
B = np.array([[1, 2, 3],
              [4, 5, 6]])

# Matrix Subtraction
C = A - B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix Subtraction:")
print(C)

Matrix A:
[[10 20 30]
 [40 50 60]]

Matrix B:
[[1 2 3]
 [4 5 6]]

Matrix Subtraction:
[[ 9 18 27]
 [36 45 54]]


Minimum Value :

In [ ]:
import numpy as np

arr = np.array([12, 45, 7, 23, 89, 5, 34])

minimum = np.min(arr)

print("Array:", arr)
print("Minimum Value:", minimum)

Array: [12 45  7 23 89  5 34]
Minimum Value: 5


Maximum Value :

In [ ]:
import numpy as np

arr = np.array([12, 45, 7, 23, 89, 5, 34])

maximum = np.max(arr)

print("Array:", arr)
print("Maximum Value:", maximum)

Array: [12 45  7 23 89  5 34]
Maximum Value: 89


Using 2D Array :

In [ ]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 5, 60],
                [70, 80, 90]])

print("Array:")
print(arr)

print("Minimum Value:", np.min(arr))
print("Maximum Value:", np.max(arr))

Array:
[[10 20 30]
 [40  5 60]
 [70 80 90]]
Minimum Value: 5
Maximum Value: 90


SCALAR:

In [ ]:
a = 10
import numpy as np

scalar = np.array(a)

print("Scalar Array:",scalar)

print("dimension :", scalar )

Scalar Array: 10
dimension : 10


Correlation :

 Positive Correlation :

In [ ]:
import numpy as np

x = np.array([10, 20, 30, 40, 50])
y = np.array([15, 25, 35, 45, 55])

correlation = np.corrcoef(x, y)

print("X =", x)
print("Y =", y)
print("Correlation Matrix:")
print(correlation)

X = [10 20 30 40 50]
Y = [15 25 35 45 55]
Correlation Matrix:
[[1. 1.]
 [1. 1.]]


Negative Correlation :

In [ ]:
import numpy as np

x = np.array([10, 20, 30, 40, 50])
y = np.array([50, 40, 30, 20, 10])

correlation = np.corrcoef(x, y)

print("X =", x)
print("Y =", y)
print("Correlation Matrix:")
print(correlation)

X = [10 20 30 40 50]
Y = [50 40 30 20 10]
Correlation Matrix:
[[ 1. -1.]
 [-1.  1.]]


User Input Correlation :

In [ ]:
import numpy as np

while True:
    try:
        n = int(input("Enter the number of elements: "))
        break
    except ValueError:
        print("Invalid input. Please enter a whole number.")

print("Enter elements for X:")
x = np.array([float(input()) for i in range(n)])

print("Enter elements for Y:")
y = np.array([float(input()) for i in range(n)])

correlation = np.corrcoef(x, y)

print("Correlation Matrix:")
print(correlation)

Enter the number of elements: 5
Enter elements for X:
1
2
3
4
5
Enter elements for Y:
10
20
30
40
50
Correlation Matrix:
[[1. 1.]
 [1. 1.]]


Eigenvalues and Eigenvectors :

In [ ]:
import numpy as np

# Create a 2x2 matrix
A = np.array([[4, 2],
              [1, 3]])

# Find eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix:")
print(A)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Matrix:
[[4 2]
 [1 3]]

Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


Important Linear Algebra Operations :

Matrix Addition

Matrix Subtraction

Matrix Multiplication

Matrix Transpose

Determinant

Inverse Matrix

Rank of Matrix

Eigenvalues and Eigenvectors

Dot Product

Cross Product


Linear algebra :

In [ ]:
import numpy as np

# Matrix A
A = np.array([[1, 2],
              [3, 4]])

# Matrix B
B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Addition
print("\nMatrix Addition:")
print(A + B)

# Subtraction
print("\nMatrix Subtraction:")
print(A - B)

# Multiplication
print("\nMatrix Multiplication:")
print(np.dot(A, B))

# Transpose
print("\nTranspose of Matrix A:")
print(A.T)

# Determinant
print("\nDeterminant of Matrix A:")
print(np.linalg.det(A))

# Inverse
print("\nInverse of Matrix A:")
print(np.linalg.inv(A))

# Rank
print("\nRank of Matrix A:")
print(np.linalg.matrix_rank(A))

# Trace
print("\nTrace of Matrix A:")
print(np.trace(A))

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

# Dot Product
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print("\nVector 1:")
print(v1)

print("\nVector 2:")
print(v2)

print("\nDot Product:")
print(np.dot(v1, v2))

# Cross Product
print("\nCross Product:")
print(np.cross(v1, v2))

# Matrix Norm
print("\nNorm of Matrix A:")
print(np.linalg.norm(A))

# Solve Linear Equation
C = np.array([[2, 1],
              [1, 3]])

D = np.array([8, 13])

solution = np.linalg.solve(C, D)

print("\nMatrix C:")
print(C)

print("\nMatrix D:")
print(D)

print("\nSolution of Linear Equation:")
print(solution)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix Subtraction:
[[-4 -4]
 [-4 -4]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Transpose of Matrix A:
[[1 3]
 [2 4]]

Determinant of Matrix A:
-2.0000000000000004

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Rank of Matrix A:
2

Trace of Matrix A:
5

Eigenvalues:
[-0.37228132  5.37228132]

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Vector 1:
[1 2 3]

Vector 2:
[4 5 6]

Dot Product:
32

Cross Product:
[-3  6 -3]

Norm of Matrix A:
5.477225575051661

Matrix C:
[[2 1]
 [1 3]]

Matrix D:
[ 8 13]

Solution of Linear Equation:
[2.2 3.6]


Salary code :

In [ ]:
basic_salary = float(input("Enter Basic Salary: "))

hra = basic_salary * 0.20
da = basic_salary * 0.10
pf = basic_salary * 0.12

gross_salary = basic_salary + hra + da
net_salary = gross_salary - pf

print("\nSalary Details")
print("Basic Salary :", basic_salary)
print("HRA (20%)    :", hra)
print("DA (10%)     :", da)
print("PF (12%)     :", pf)
print("Gross Salary :", gross_salary)
print("Net Salary   :", net_salary)

Enter Basic Salary: 10000

Salary Details
Basic Salary : 10000.0
HRA (20%)    : 2000.0
DA (10%)     : 1000.0
PF (12%)     : 1200.0
Gross Salary : 13000.0
Net Salary   : 11800.0


Standard Deviation :

In [ ]:
import numpy as np

# Get the number of elements
n = int(input("Enter the number of elements: "))

# Create an empty list
data = []

# Read the elements
for i in range(n):
    value = float(input(f"Enter element {i+1}: "))
    data.append(value)

# Convert the list to a NumPy array
arr = np.array(data)

# Calculate statistics
mean = np.mean(arr)
variance = np.var(arr)
standard_deviation = np.std(arr)

# Display the results
print("\nArray:", arr)
print("Mean:", mean)
print("Variance:", variance)
print("Standard Deviation:", standard_deviation)

Enter the number of elements: 5
Enter element 1: 10
Enter element 2: 20
Enter element 3: 30
Enter element 4: 40
Enter element 5: 50

Array: [10. 20. 30. 40. 50.]
Mean: 30.0
Variance: 200.0
Standard Deviation: 14.142135623730951


Pandas Series :

In [ ]:
# Import pandas
import pandas as pd

# Create a Series using list
marks = pd.Series([85, 90, 75, 95, 88])

# Display Series
print("Student Marks Series:")
print(marks)

# Access values using index
print("\nFirst Mark:")
print(marks[0])

# Display index
print("\nIndex Values:")
print(marks.index)

# Display actual values
print("\nSeries Values:")
print(marks.values)

# Series calculations
print("\nTotal Marks:", marks.sum())
print("Average Marks:", marks.mean())
print("Maximum Mark:", marks.max())
print("Minimum Mark:", marks.min())

Student Marks Series:
0    85
1    90
2    75
3    95
4    88
dtype: int64

First Mark:
85

Index Values:
RangeIndex(start=0, stop=5, step=1)

Series Values:
[85 90 75 95 88]

Total Marks: 433
Average Marks: 86.6
Maximum Mark: 95
Minimum Mark: 75


Pandas Data Frame :

In [ ]:
import pandas as pd

# Create DataFrame
data = {
    "Name": ["Gokul", "Naveen", "Sanjay", "Vishnu"],
    "Age": [20, 21, 22, 23],
    "Marks": [85, 90, 75, 95],
    "Department": ["IT", "CSE", "ECE", "MECH"]
}

df = pd.DataFrame(data)

# Display DataFrame
print(df)

     Name  Age  Marks Department
0   Gokul   20     85         IT
1  Naveen   21     90        CSE
2  Sanjay   22     75        ECE
3  Vishnu   23     95       MECH


Pandas Series :

In [ ]:
import pandas as pd

# Create Series
name = pd.Series(["Gokul", "Naveen", "Sanjay", "Vishnu"])
age = pd.Series([20, 21, 22, 23])
marks = pd.Series([85, 90, 75, 95])
department = pd.Series(["IT", "CSE", "ECE", "MECH"])

# Display Series
print("Name Series:")
print(name)

print("\nAge Series:")
print(age)

print("\nMarks Series:")
print(marks)

print("\nDepartment Series:")
print(department)

Name Series:
0     Gokul
1    Naveen
2    Sanjay
3    Vishnu
dtype: object

Age Series:
0    20
1    21
2    22
3    23
dtype: int64

Marks Series:
0    85
1    90
2    75
3    95
dtype: int64

Department Series:
0      IT
1     CSE
2     ECE
3    MECH
dtype: object


DataFrame and Save it as CSV File using Pandas :

In [ ]:
import pandas as pd

# Create DataFrame
data = {
    "Name": ["Gokul", "Naveen", "Sanjay", "Vishnu"],
    "Age": [20, 21, 22, 23],
    "Marks": [85, 90, 75, 95],
    "Department": ["IT", "CSE", "ECE", "MECH"]
}

df = pd.DataFrame(data)

# Display DataFrame
print(df)

# Save DataFrame to CSV file
df.to_csv("student_data.csv", index=False)

print("CSV file saved successfully")

     Name  Age  Marks Department
0   Gokul   20     85         IT
1  Naveen   21     90        CSE
2  Sanjay   22     75        ECE
3  Vishnu   23     95       MECH
CSV file saved successfully


Multiple colums:

In [ ]:
import pandas as pd

data = {
    "Name": ["Gokul", "Naveen", "Sanjay", "Vishnu"],
    "Age": [20, 21, 22, 23],
    "Marks": [85, 90, 75, 95],
    "Department": ["IT", "CSE", "ECE", "MECH"]
}

df = pd.DataFrame(data)

# Selecting multiple columns using two brackets
result = df[["Name", "Marks"]]

print(result)

     Name  Marks
0   Gokul     85
1  Naveen     90
2  Sanjay     75
3  Vishnu     95


Pandas Row Selecting Code :

In [ ]:
import pandas as pd

# Create DataFrame
data = {
    "Name": ["Gokul", "Naveen", "Sanjay", "Vishnu"],
    "Age": [20, 21, 22, 23],
    "Marks": [85, 90, 75, 95],
    "Department": ["IT", "CSE", "ECE", "MECH"]
}

df = pd.DataFrame(data)

# Display complete DataFrame
print("Original DataFrame:")
print(df)


# 1. Select first row using iloc
print("\nFirst Row:")
print(df.iloc[0])


# 2. Select multiple rows using iloc
print("\nFirst Two Rows:")
print(df.iloc[0:2])


# 3. Select last row using iloc
print("\nLast Row:")
print(df.iloc[-1])


# 4. Select row using loc
print("\nRow with Index 2:")
print(df.loc[2])


# 5. Select specific rows and columns
print("\nSelect Rows and Columns:")
print(df.loc[0:2, ["Name", "Marks"]])


# 6. Select rows using condition
print("\nStudents Marks Greater Than 80:")
result = df[df["Marks"] > 80]
print(result)


# 7. Select rows based on age
print("\nStudents Age Greater Than 21:")
result = df[df["Age"] > 21]
print(result)

Original DataFrame:
     Name  Age  Marks Department
0   Gokul   20     85         IT
1  Naveen   21     90        CSE
2  Sanjay   22     75        ECE
3  Vishnu   23     95       MECH

First Row:
Name          Gokul
Age              20
Marks            85
Department       IT
Name: 0, dtype: object

First Two Rows:
     Name  Age  Marks Department
0   Gokul   20     85         IT
1  Naveen   21     90        CSE

Last Row:
Name          Vishnu
Age               23
Marks             95
Department      MECH
Name: 3, dtype: object

Row with Index 2:
Name          Sanjay
Age               22
Marks             75
Department       ECE
Name: 2, dtype: object

Select Rows and Columns:
     Name  Marks
0   Gokul     85
1  Naveen     90
2  Sanjay     75

Students Marks Greater Than 80:
     Name  Age  Marks Department
0   Gokul   20     85         IT
1  Naveen   21     90        CSE
3  Vishnu   23     95       MECH

Students Age Greater Than 21:
     Name  Age  Marks Department
2  Sanjay   22   

Handling Missing Values in Pandas:

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Gokul", "Naveen", "Sanjay", "Vishnu"],
    "Age": [20, 21, None, 23],
    "Marks": [85, None, 75, 95],
    "Department": ["IT", "CSE", None, "MECH"]
}

df = pd.DataFrame(data)

print(df)

     Name   Age  Marks Department
0   Gokul  20.0   85.0         IT
1  Naveen  21.0    NaN        CSE
2  Sanjay   NaN   75.0       None
3  Vishnu  23.0   95.0       MECH


In [ ]:
from google.colab import files

uploded = files.upload()

Saving Titanic-Dataset.csv to Titanic-Dataset.csv
